spring:
  profiles:
    active: dev

---
server:
  port: 8088
spring:
  profiles: prod
  application:
    name: syedu-config-client
  cloud:
    config:
      uri: http://localhost:6061
      label: master
      profile: prod


---
server:
  port: 8087
spring:
  profiles: dev
  application:
    name: syedu-config-client
  cloud:
    config:
      uri: http://localhost:6061
      label: master
      profile: dev